import Head from 'next/head';
import Link from 'next/link';
import React, { useContext, useEffect, useState } from 'react';
import { Store } from '../utils/Store';
import styles from '../styles/Layout.module.css';

export default function Layout({ title, children }) {
  const { state } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);
  return (
    <>
      <Head>
        <title>{title ? title + ' - Kustom Art' : 'Kustom Art'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header>
          <nav className={styles.navheader}>
            <Link href="/">
              <a className={styles.navlogo}>Kustom Art</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className={styles.navlink}>
                  Carrinho
                  {cartItemsCount > 0 && (
                    <span className={styles.cart}>{cartItemsCount}</span>
                  )}
                </a>
              </Link>
              <Link href="/login">
                <a className={styles.a}>Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>Footer</footer>
      </div>
    </>
  );
}
