import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Layout.module.css';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Kustom Art' : 'Kustom Art'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header>
          <nav className={styles.navheader}>
            <Link href="/">
              <a className={styles.navlogo}>Kustom Art</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className={styles.navlink}>Carrinho</a>
              </Link>
              <Link href="/login">
                <a className={styles.a}>Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>Footer</footer>
      </div>
    </>
  );
}
