import Head from 'next/head';
import Link from 'next/link';
import React, { useContext, useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Store } from '../utils/Store';
import styles from '../styles/Layout.module.css';
import { Menu, MenuButton, MenuItem, MenuList } from '@chakra-ui/react';
import DropDownLink from './DropDownLink';

export default function Layout({ title, children }) {
  const { status, data: session } = useSession();

  const { state } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);
  return (
    <>
      <Head>
        <title>{title ? title + ' - Kustom Art' : 'Kustom Art'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position="bottom-center" limit={1} />
      <div className={styles.container}>
        <header>
          <nav className={styles.navheader}>
            <Link href="/">
              <a className={styles.navlogo}>Kustom Art</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className={styles.navlink}>
                  Carrinho
                  {cartItemsCount > 0 && (
                    <span className={styles.cart}>{cartItemsCount}</span>
                  )}
                </a>
              </Link>
              {status === 'loading' ? (
                'Loading'
              ) : session?.user ? (
                <Menu as="div">
                  <MenuButton bg="#FFF" fontSize="1rem">
                    {session.user.name}
                  </MenuButton>
                  <MenuList>
                    <MenuItem bg="#FFF" fontSize="1rem">
                      <DropDownLink href="/profile">Conta</DropDownLink>
                    </MenuItem>
                  </MenuList>
                </Menu>
              ) : (
                <Link href="/login">
                  <a className={styles.a}>Login</a>
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>Footer</footer>
      </div>
    </>
  );
}
