const data = {
  products: [
    {
      name: 'Moletom',
      slug: 'Jaqueta',
      category: 'Jaqueta',
      image: '/images/jaquet1.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Jaqueta',
      slug: 'Jaqueta',
      category: 'Jaqueta',
      image: '/images/jaquet2.png',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Jaqueta',
      slug: 'Jaqueta',
      category: 'Jaqueta',
      image: '/images/jaquet3.png',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Jaqueta',
      slug: 'Jaqueta',
      category: 'Jaqueta',
      image: '/images/jaquet4.png',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Calça',
      slug: 'Calça',
      category: 'Calça',
      image: '/images/pants1.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Calça top de linha',
    },
    {
      name: 'Calça',
      slug: 'Calça',
      category: 'Calça',
      image: '/images/pants2.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Calça top de linha',
    },
    {
      name: 'Camisa',
      slug: 'Camisa',
      category: 'Camisa',
      image: '/images/t-shirt-male.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Camisa top de linha',
    },
    {
      name: 'Camisa',
      slug: 'Camisa',
      category: 'Camisa',
      image: '/images/t-shirt-female.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Camisa top de linha',
    },
  ],
};

export default data;
