import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Maria',
      email: 'admina@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Moletom1',
      slug: 'Moletom1',
      category: 'Jaqueta',
      image: '/images/jaquet1.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Jaqueta1',
      slug: 'Jaqueta1',
      category: 'Jaqueta',
      image: '/images/jaquet2.png',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Jaqueta2',
      slug: 'Jaqueta2',
      category: 'Jaqueta',
      image: '/images/jaquet3.png',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Jaqueta3',
      slug: 'Jaqueta3',
      category: 'Jaqueta',
      image: '/images/jaquet4.png',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Jaqueta top de linha',
    },
    {
      name: 'Calça1',
      slug: 'Calça1',
      category: 'Calça',
      image: '/images/pants1.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Calça top de linha',
    },
    {
      name: 'Calça2',
      slug: 'Calça2',
      category: 'Calça',
      image: '/images/pants2.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Calça top de linha',
    },
    {
      name: 'Camisa1',
      slug: 'Camisa1',
      category: 'Camisa',
      image: '/images/t-shirt-male.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Camisa top de linha',
    },
    {
      name: 'Camisa2',
      slug: 'Camisa2',
      category: 'Camisa',
      image: '/images/t-shirt-female.jpg',
      price: 500,
      brand: 'Kustom Art',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'Camisa top de linha',
    },
  ],
};

export default data;
